#! /bin/sh

DESC="gogadgets"
NAME=gogadgets
DAEMON=/usr/local/bin/gogadgets
DAEMON_OPTS="-c /etc/gogadgets/config.json"

test -f $DAEMON || exit 0

set -e

case "$1" in
    start)
        echo -n "Starting $DESC: "
        start-stop-daemon --start --background --quiet --pidfile /var/run/$NAME.pid \
                          --exec $DAEMON -- $DAEMON_OPTS
        echo "$NAME."
        ;;
    stop)
        echo -n "Stopping $DESC: "
        start-stop-daemon --stop --quiet --pidfile /var/run/$NAME.pid
        # \--exec $DAEMON
        echo "$NAME."
        ;;
    restart|force-reload)
        echo -n "Restarting $DESC: "
        start-stop-daemon --stop --quiet --pidfile \
                          /var/run/$NAME.pid
        sleep 1
        start-stop-daemon --start --quiet --pidfile \
                          /var/run/$NAME.pid --exec $DAEMON
        echo "$NAME."
        ;;
    *)
        N=/etc/init.d/$NAME
        # echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
        echo "Usage: $N {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac
